backend:
  name: git-gateway  # 改成这个，就不需要配置复杂的 OAuth 了
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "tasks"
    label: "悬赏任务"
    folder: "tasks"
    create: true
    extension: "json"
    format: "json"
    fields:
      - { label: "编号", name: "id", widget: "string" }
      - { label: "描述", name: "desc", widget: "text" }
      - { label: "图片", name: "img", widget: "image" }
      - { label: "金额", name: "price", widget: "string" }
